development:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>

test:
  secret_key_base: 'd9ae5ae815e36df08af39e32b56257e6fd28e0ec78bac8baec5cf6050945ac54534c0c4a3fd0c100466991d5682b97c1b84bd1e007697e39da5575ccc58a7d7c'

staging:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>

beta:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>

production:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>
